// <auto-generated />
using Api_Vapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Api_Vapp.Migrations
{
    [DbContext(typeof(Api_Context))]
    [Migration("20260724114800_AddPublicParticipantPhoneVerified")]
    partial class AddPublicParticipantPhoneVerified
    {
    }
}
